### ISSUE TITLE
SciDAVis no longer compiles against muParser >=2.3.1

### ISSUE THREAD

**Issue by AbsolutHacker** [highperformancecoder/scidavis-old#139]
SciDAVis does not compile against [muParser v2.3.1](https://github.com/beltoforion/muparser/releases/tag/v2.3.1) because libscidavis' MyParser extends mu::Parser, which [has been declared final recently](https://github.com/beltoforion/muparser/commit/111819c78b64ab59c9d76114370d8efc2c271a41) by @beltoforion.
Unfortunately, I seem to have lost the error message, but will reproduce shortly.

**Comment by beltoforion** [comment]
I have unfinalized it. Please try the head revision

**Comment by AbsolutHacker** [comment]
Thank you very much. That solves (this) compilation issue!
Also, out of curiosity: would there be a palpable benefit from declaring muParser final? If so, libscidavis might be able to switch to extending muParser's base class; at first glance I didn't find any obvious necessity of extending muParser.
But since I am neither really familiar with the project nor C++ in general, this is just speculation.

**Comment by beltoforion** [comment]
No there is no benefit from declaring it final. I did it because there was an old /* final */ comment in front of the class. That was a convention that was sometimes used prior to C++11 to signal that a class should not be derived further. However there is nothing that speaks against doing it. It is perfectly safe. (I myself did subclass ParserBase, so i cannot blame anyone who did it with the parser class)

The code is quite old and I probably originally intended it to be final because the virtual function calls like InitCharSets, InitFun, InitConst and InitOprt do not work in the constructor. (The function call will work, just not as a virtual function.) However these specific functions will never really be used as virtual functions anyway so they should not even exist as virtual functions.

I did not remove those functions from parserbase because i do not want to break more API than necessary with this release. It is such a long time since the last release and i'd like to make existing software safer and not cause too much work.
