### ISSUE TITLE
Unable to complete step 6（macOS）

### ISSUE THREAD

**Issue by ZDYYY** [highperformancecoder/scidavis-old#156]
Thank you for your interest, I'm a newbie who is not very good at coding.
I have completed the fourth step as described in the installation text.
In step 5, an additional path is added with the `vi .bash_profile `command.
However, in step 6, it keeps saying that the command cannot be found.
What is the problem? Please try to make it as simple as possible, because it may be very difficult for me!
Thank you very much.
![image](https://user-images.githubusercontent.com/36835121/99896423-57536b00-2ccb-11eb-8905-1c76cf0d9711.png)

**Comment by highperformancecoder** [comment]
It seems like you are using an out of date set of instructions.

The official instructions are at
https://github.com/highperformancecoder/scidavis/blob/master/INSTALL.md,
which I can see have not been updated for SciDaVis 2.x

I'm guessing your attempting to build SciDaVis using the MacPorts
instructions. To be truthful, we haven't figured out how to build
SciDaVis 2.x on Macs, which is why the latest Mac build is 1.26.

There is not a lot of functional difference between SciDaVis 1.x and
2.x - the primary reason for the version bump is the move to Python
3.x, from the earlier Python 2.x. But python scripting doesn't work
too well on Macs anyway, so this is no biggie. The other major
difference is the move to Qt5, again not affecting SciDaVis
functionality.

There is a SciDaVis 3.x under development, which eschews PyQt in
favour of Classdesc for python bindings. This should solve all the
issues with python on Windows and Macs, but has been stalled for the
last 12 months due to lack of time on my part. I cannot make any
commitments as to when I'll get back to fixing that up.

Cheers

On Sat, Nov 21, 2020 at 10:02:43PM -0800, ZDYYY wrote:
> Thank you for your interest, I'm a newbie who is not very good at coding.
> I have completed the fourth step as described in the installation text.
> In step 5, an additional path is added with the vi .bash_profile command.
> However, in step 6, it keeps saying that the command cannot be found.
> What is the problem? Please try to make it as simple as possible, because it
> may be very difficult for me!
> Thank you very much.
> image
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by ZDYYY** [comment]
> 似乎您正在使用过期的说明集。官方说明位于 https://github.com/highperformancecoder/scidavis/blob/master/INSTALL.md，据我所知SciDaVis 2.x尚未更新。我猜您正在尝试使用MacPorts指令构建SciDaVis。老实说，我们还没有弄清楚如何在Mac上构建SciDaVis 2.x，这就是为什么最新的Mac版本是1.26。SciDaVis 1.x和2.x之间没有太多功能上的区别-版本增加的主要原因是从早期的Python 2.x迁移到Python3.x。但是无论如何，Python脚本在Mac上仍然不能很好地工作，因此这并不是什么大问题。另一个主要区别是向Qt5的迁移，再次不影响SciDaVis的功能。有一个正在开发的SciDaVis 3.x，它避开了PyQt，而推荐使用Classdesc进行python绑定。这应该可以解决Windows和Mac上python的所有问题，但是由于缺乏时间，在过去的12个月中一直处于停滞状态。关于何时恢复修复，我无法做出任何承诺。干杯
> […](#)
> On Sat, Nov 21, 2020 at 10:02:43PM -0800, ZDYYY wrote: Thank you for your interest, I'm a newbie who is not very good at coding. I have completed the fourth step as described in the installation text. In step 5, an additional path is added with the vi .bash_profile command. However, in step 6, it keeps saying that the command cannot be found. What is the problem? Please try to make it as simple as possible, because it may be very difficult for me! Thank you very much. image — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.*
> --
> ---------------------------------------------------------------------------- Dr Russell Standish Phone 0425 253119 (mobile) Principal, High Performance Coders hpcoder@hpcoders.com.au http://www.hpcoders.com.au ----------------------------------------------------------------------------

Thank you for your response, and I know this is not an easy project!
According to you, there is no clear installation manual for this project on macOS right now, is that right?
Can you recommend a similar software for me, mainly for simple data processing (with a common file format)?
Thank you very much.

**Comment by highperformancecoder** [comment]
On Sun, Nov 22, 020 at 11:55:12PM -0800, ZDYYY wrote:
>     On Sat, Nov 21, 2020 at 10:02:43PM -0800, ZDYYY wrote: Thank you for your
>     interest, I'm a newbie who is not very good at coding. I have completed the
>     fourth step as described in the installation text. In step 5, an additional
>     path is added with the vi .bash_profile command. However, in step 6, it
>     keeps saying that the command cannot be found. What is the problem? Please
>     try to make it as simple as possible, because it may be very difficult for
>     me! Thank you very much.

Why do you need to build from source code? Couldn't you just use the
1.26 prebuilt version for MacOSX?


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------
