### ISSUE TITLE
Future prospects ?

### ISSUE THREAD

**Issue by narunlifescience** [highperformancecoder/scidavis-old#8]
is scidavis still in development ? what would be the future prospects of scidavis ?

**Comment by highperformancecoder** [comment]
Scidavis is being actively maintained, but is seriously under
resourced. Expect bug fixes only, at this point in time, rather than
significant feature development.

On Thu, Jan 21, 2016 at 02:49:19AM -0800, Arun Narayanankutty wrote:

> is scidavis still in development ? what would be the future prospects of scidavis ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/issues/8

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by narunlifescience** [comment]
Thank you for the response!
